server:
    port: 8085

spring:
    main:
        banner-mode: "off"
    jersey:
       application-path: /api

logging:
    file: "D:/Maven/api/target/logs/crud_app_log_file.log"
    level:
        org:
            springframework: INFO
